version: '3.8'

services:
  app:
    build: .
    container_name: src
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certificates:/etc/nginx/certificates
    depends_on:
      - s