version: '3.8'

services:
  web:
    build: .
    ports:
      - "443:443"
    volumes:
      - "/etc/letsencrypt/live/api.meet-sync.us/fullchain.pem:/certs/fullchain.pem:ro"
      - "/etc/letsencrypt/live/api.meet-sync.us/privkey.pem:/certs/privkey.pem:ro"
      - .:/src
    environment:
      - DEBUG=True
