name: CD Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH into GCP and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSHKEY }}
          script: |
            cd /home/${{ secrets.GCP_USER }}/meetsync-backend
            sudo -u home bash ./deploy.sh

