name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade -r requirements.txt

      - name: Run Tests
        run: |
          python -m pytest tests/

  deploy-dev:
    needs: build-test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH into GCP and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSHKEY }}
          script: |
            cd /home/${{ secrets.GCP_USER }}/meetsync-backend
            sudo -u home bash ./deploy.sh dev

  deploy-prod:
    needs: build-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH into GCP and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.GCP_IP }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSHKEY }}
          script: |
            cd /home/${{ secrets.GCP_USER }}/meetsync-backend
            sudo -u home bash ./deploy.sh prod
